### ISSUE TITLE
google places complete android 2.3

### ISSUE THREAD

**Issue by croccio** [pushbit/sprockets#11]
can you add support for android 2.3 api 9 for autocomplete places widget please?

**Comment by pushbit** [comment]
I just tested `GooglePlaceAutoComplete` with API 10 (API 9 emulator is no longer available) and it seems to be working.  Even though Sprockets has `minSdkVersion 16`, many of the features are compatible with lower API versions.  You just have to ask the build system to allow it.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="your.package.name">

    <uses-sdk tools:overrideLibrary="net.sf.sprockets, android.support.v13"/>
```

Give it a try and let me know if it's working for you.

**Comment by croccio** [comment]
i cannot compile i get an error TOP-LEVEL-EXCEPTION. it ca depends from support lib i've removed them from my prom but i get same error.

**Comment by pushbit** [comment]
Can you list your `dependencies`?  It seems that there may be a duplicate somewhere.  Possibly also try `Build > Rebuild Project` from the menu, in case that helps after removing the duplicate dependencies.
