### ISSUE TITLE
googleplace search

### ISSUE THREAD

**Issue by croccio** [pushbit/sprockets#12]
googleplace search doesn't show dropdown. how can i show it? also example doesn't work

**Comment by pushbit** [comment]
Are you referring to the sample app?  The Google Places API samples require an API key.  This is step 4 in [Sprockets Install][1] and should be done in the `samples` module.

[1]: https://github.com/pushbit/sprockets/tree/master/android#install

**Comment by croccio** [comment]
I cannot Found file in sample app . Ill try to put file 

Inviato da iPhone

**Comment by croccio** [comment]
where i've to put that file? if i put tin src/main/resources/ andoird studio give me error for tag sprockets and google and it cannot compile. please update your sample with that file

**Comment by pushbit** [comment]
`src/main/resources/` is the correct location.  Are you sure that it doesn't compile?  I get a Lint issue, "Namespace is not bound", but it still compiles without problem.  I believe the Lint issue can be ignored.

I will add `sprockets.xml` to the samples app in the next release.

**Comment by croccio** [comment]
canc lose, i've solved. thank you
