### ISSUE TITLE
custom google place search

### ISSUE THREAD

**Issue by croccio** [pushbit/sprockets#13]
can i set new style for edit text?? so for example background selector drawable and other???

**Comment by pushbit** [comment]
Yes, `GooglePlaceAutoComplete` is an `AutoCompleteTextView` and you can set the same style attributes.  You can also set a custom TextView layout resource that will be used for each autocomplete suggestion.  See the [Javadoc][1] for all of the options.

[1]: https://pushbit.github.io/sprockets/android/apidocs/index.html?net/sf/sprockets/widget/GooglePlaceAutoComplete.html

**Comment by croccio** [comment]
thankyou. you cn close
