### ISSUE TITLE
getLatitude() and getLongitude() return -Infinity

### ISSUE THREAD

**Issue by croccio** [pushbit/sprockets#14]
getLatitude() and getLongitude() return -Infinity

    Intent intent = new Intent("ADDRESS_CHANGED");
                intent.putExtra("address", prediction.getName());
                intent.putExtra("latitude", prediction.getLatitude());
                intent.putExtra("longitude", prediction.getLongitude());
                LocalBroadcastManager.getInstance(getActivity()).sendBroadcast(intent);

**Comment by pushbit** [comment]
Please see #10 for the solution.
