### ISSUE TITLE
Wrong status output?

### ISSUE THREAD

**Issue by demongut** [pushbit/sprockets#15]
Hi, I am getting the wrong status for this query:
---
CODE

Response<List<Place>> resp = Places.nearbySearch(Params.create().longitude(-10.460491).latitude(137.895137).radius(50000).keyword("shop"));
String status = resp.getStatus();
System.out.println(status);

----
OUTPUT: INVALID_REQUEST
---
BUT 

Response<List<Place>> resp = Places.nearbySearch(Params.create().longitude(-10.460491).latitude(13.895137).radius(50000).keyword("shop")); 

WORKS - "ZERO_RESULTS"?

**Comment by pushbit** [comment]
I suspect the 'INVALID_REQUEST' status is due to the latitude value.  Valid latitudes range from -90 to 90.  Perhaps the latitude and longitude values are reversed?

**Comment by demongut** [comment]
Sorry, im geographically ignorant so how do I reference this place:

https://goo.gl/maps/JC64deJau8R2

**Comment by demongut** [comment]
Nevermind, I'm so dumb.
